"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
$username\
$shell\
$sudo\
[](bg:mauve fg:red)\
$directory\
[](fg:mauve bg:blue)\
$git_status\
$git_branch\
[](fg:blue bg:sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
[](fg:sapphire bg:surface1)\
$docker_context\
$conda\
[](fg:surface1 bg:base)\
$time\
[ ](fg:base)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#e3e5e5"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:red fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
NixOS = ""

[username]
show_always = false
style_user = "bg:red fg:text"
style_root = "bg:red fg:text"
format = '[ $user]($style)'

[shell]
disabled = false
bash_indicator = '󱆃'
fish_indicator = '󰈺'
zsh_indicator = ''
powershell_indicator = ''
pwsh_indicator = ''
unknown_indicator = '?_'
format = '[ $indicator ]($style)'
style = "bg:red fg:text"

[sudo]
disabled = false
style = "bg:red fg:text"
symbol = '󱕴 '
format = '[$symbol]($style)'

# Directory section

[directory]
style = "fg:text bg:mauve"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_status]
style = "bg:blue"
format = '[[  ($all_status$ahead_behind)](fg:text bg:blue)]($style)'

[git_branch]
symbol = ""
ignore_branches = ['master', 'main']
style = "bg:blue"
format = '[[ $symbol $branch ](fg:text bg:blue)]($style)'

# Programming languages

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[c]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[rust]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[golang]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[php]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[kotlin]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[haskell]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[python]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

[lua]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:text bg:sapphire)]($style)'

# Context

[docker_context]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $context) ](fg:#83a598 bg:surface1)]($style)'

[conda]
style = "bg:surface1"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:surface1)]($style)'

[nix_shell]
disabled = true
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue) '

# Time / final section

[time]
disabled = false
time_format = "%R"
style = "bg:crust"
format = '[[  $time ](fg:text bg:base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
