-- Animations
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
--
-- Off, deliberately. See item 22 of docs/plans/desktop-design.md.
--
-- The desktop is faster without motion and the previous settings were well
-- over any sensible budget: layersIn ran at 400ms, so rofi spent four tenths
-- of a second fading in before it was usable; windows opened in 300ms.
--
-- Motion earns its cost when it tells you something the end state does not,
-- and the case that usually makes - orientation after a change of focus - is
-- already covered here by the border colour. An instantly recoloured border
-- is the better cue anyway: there is no window in which the answer is
-- ambiguous.
--
-- ONE animation carried information the end state does not, and it is named
-- here so that missing it is recognised rather than puzzling: the workspace
-- slide told you which direction you moved. Switching 3 -> 4 now replaces the
-- screen at once with no cue about left or right. If that is missed after
-- real use, bring back `workspaces` alone at speed 1 (100ms) and nothing
-- else:
--
--   hl.config({ animations = { enabled = true } })
--   hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1} } })
--   hl.animation({ leaf = "global", enabled = false })
--   hl.animation({ leaf = "workspaces", enabled = true, speed = 1, bezier = "almostLinear", style = "slide" })
--
-- The full set of curves and per-leaf animations this file used to hold is in
-- the history if a larger revert is ever wanted.

hl.config({ animations = { enabled = false } })
