# Hardware configuration for homelab02
# This file will be auto-generated by nixos-anywhere using:
#   --generate-hardware-config nixos-generate-config ./hosts/homelab02/hardware.nix
#
# If installing manually, generate with:
#   sudo nixos-generate-config --root /mnt --show-hardware-config > hardware.nix
#
# PLACEHOLDER - Replace with actual hardware configuration before first boot
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # These will be populated by nixos-generate-config
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Filesystem mounts are handled by disko - do not duplicate here
  # If you see fileSystems entries here after generation, remove them
  # as disko.nix handles all disk configuration

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
