# Called by Jellyfin to post-process live TV recordings
# Enables automatically skipping through advertisements
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.cg.service.comskip;

  # Helper to convert a value to INI format string
  valueToIniString =
    value:
    if lib.isBool value then
      (if value then "1" else "0")
    else if lib.isInt value then
      toString value
    else if lib.isString value then
      value
    else
      throw "Unsupported value type in comskip settings: ${builtins.typeOf value}";

  # Generate INI file content from attribute set
  settingsToIni =
    settings:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "${name}=${valueToIniString value}") settings
    );

  # Helper script that Jellyfin will call
  postProcessScript = pkgs.writeShellScript "jellyfin-comskip" ''
    set -euo pipefail

    # Jellyfin passes the full path to the recording
    VIDEO_FILE="$1"

    if [ ! -f "$VIDEO_FILE" ]; then
      echo "ERROR: Video file does not exist: $VIDEO_FILE" >&2
      exit 1
    fi

    VIDEO_DIR=$(dirname "$VIDEO_FILE")
    VIDEO_BASE=$(basename "$VIDEO_FILE" .ts)
    EDL_FILE="$VIDEO_DIR/$VIDEO_BASE.edl"

    # Skip if EDL already exists
    if [ -f "$EDL_FILE" ]; then
      echo "EDL already exists for $VIDEO_FILE, skipping"
      exit 0
    fi

    echo "Starting comskip processing for: $VIDEO_FILE"
    echo "Working directory: $VIDEO_DIR"

    # Change to the video directory so comskip outputs files there
    cd "$VIDEO_DIR"

    # Run comskip
    ${pkgs.comskip}/bin/comskip \
      --ini=${config.environment.etc."comskip/comskip.ini".source} \
      "$VIDEO_FILE"

    if [ -f "$EDL_FILE" ]; then
      echo "SUCCESS: Created EDL file at $EDL_FILE"
      exit 0
    else
      echo "WARNING: Comskip completed but no EDL file was created"
      exit 0
    fi
  '';

in
{
  options.cg.service.comskip = {
    enable = lib.mkEnableOption "Comskip commercial detection";

    settings = lib.mkOption {
      type = lib.types.attrs;
      default = { };
      description = "Comskip configuration settings (comskip.ini format)";
    };
  };

  config = lib.mkIf cfg.enable {
    # Install comskip package
    environment.systemPackages = [ pkgs.comskip ];

    # Generate comskip.ini configuration
    environment.etc."comskip/comskip.ini".text =
      let
        # Merge user settings with required defaults
        allSettings = cfg.settings // {
          # Ensure these critical settings are always present
          output_edl = 1;
          output_videoredo = 0;
          output_projectx = 0;
          output_default = 0;
        };
      in
      "# Generated by NixOS comskip module\n" + settingsToIni allSettings;

    # Make the post-processing script available at a well-known location
    environment.etc."jellyfin/comskip-post-process".source = postProcessScript;
  };
}
