# Called by Jellyfin to post-process live TV recordings
# Enables automatically skipping through advertisements
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.cg.service.comskip;

  # Helper to convert a value to INI format string
  valueToIniString =
    value:
    if lib.isBool value then
      (if value then "1" else "0")
    else if lib.isInt value then
      toString value
    else if lib.isString value then
      value
    else
      throw "Unsupported value type in comskip settings: ${builtins.typeOf value}";

  # Generate INI file content from attribute set
  settingsToIni =
    settings:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "${name}=${valueToIniString value}") settings
    );

in
{
  options.cg.service.comskip = {
    enable = lib.mkEnableOption "Comskip commercial detection";

    settings = lib.mkOption {
      type = lib.types.attrs;
      default = { };
      description = "Comskip configuration settings (comskip.ini format)";
    };
  };

  config = lib.mkIf cfg.enable {
    # Install comskip package
    environment.systemPackages = [ pkgs.comskip ];

    # Generate comskip.ini configuration
    environment.etc."comskip/comskip.ini".text =
      let
        # Merge user settings with required defaults
        allSettings = cfg.settings // {
          # Ensure these critical settings are always present
          output_edl = 1;
          output_videoredo = 0;
          output_projectx = 0;
          output_default = 0;
        };
      in
      "# Generated by NixOS comskip module\n" + settingsToIni allSettings;
  };
}
