# Cross-seed - Private Tracker Ratio Builder (v6)
# Finds torrents on your private trackers that match content you already have
# Pure upload - no additional downloads required
#
# HOW IT WORKS:
# 1. Scans your existing media library and qBittorrent torrent files
# 2. Searches your private trackers (via Torznab from Prowlarr) for matches
# 3. Injects matching torrents into qBittorrent using hardlinks for seeding
#
# SOPS SECRETS REQUIRED:
# - media-stack/prowlarr/api         (Prowlarr API key for Torznab feeds)
# - media-stack/qbittorrent/username (qBittorrent WebUI username)
# - media-stack/qbittorrent/password (qBittorrent WebUI password - will be URL-encoded)
#
# SETUP AFTER DEPLOYMENT:
# 1. Get your Prowlarr API key: Prowlarr -> Settings -> General -> API Key
# 2. Add it to your sops secrets at media-stack/prowlarr/api
# 3. Get Torznab indexer IDs from Prowlarr:
#    - Go to Prowlarr -> Indexers
#    - Click on a PRIVATE tracker -> note the ID in the URL (e.g., /indexers/1)
#    - Or use "Copy Torznab Feed" and extract the ID
# 4. Update the torznabIndexerIds option with your private tracker IDs
# 5. Rebuild and the config.js will be generated with your secrets
#
# CHECKING CROSS-SEED:
# - Logs: podman logs -f cross-seed
# - API key: podman exec cross-seed cross-seed api-key
# - Web UI: http://hostname:2468 (if not behind VPN)
#
# IMPORTANT:
# - Only add PRIVATE trackers - public trackers provide little ratio benefit
# - Cross-seed runs through VPN if qbittorrent.vpn.enable = true
# - Hardlinks require cross-seed and qBittorrent to see the same paths
#
# NOTE ON QBITTORRENT PASSWORD:
# The password is embedded in a URL, so special characters need URL-encoding.
# If your password contains special characters (@, :, /, etc.), either:
# 1. Use a simpler password for qBittorrent, or
# 2. Manually URL-encode special characters in your sops secret
#    (e.g., @ becomes %40, : becomes %3A)
#
# NETWORK ARCHITECTURE:
# - When VPN enabled: cross-seed uses --network=container:gluetun, sharing gluetun's
#   network namespace. This means it accesses qBittorrent via localhost:8080 since
#   qBittorrent also shares gluetun's network.
# - When VPN disabled: cross-seed uses arr-network and accesses qBittorrent via
#   its container hostname.
# - Prowlarr is always accessed via the reverse proxy (prowlarr.gyarmathy.co)
#   since it's on the arr-network and cross-seed needs a stable route to it.
#
# MIGRATION NOTES (homelab02 NAS):
# Cross-seed will MOVE to homelab02 alongside qBittorrent.
# - Needs access to qBittorrent's torrent files and media library
# - Both are on the same host, so this is straightforward
{
  config,
  lib,
  ...
}:

let
  cfg = config.cg.service.cross-seed;
  stack = config.cg.service.media-stack;
  qbt = config.cg.service.qbittorrent;

  # Helper functions for JavaScript value formatting
  boolToJs = b: if b then "true" else "false";
  nullableToJs = v: if v == null then "null" else toString v;

  # Determine the correct qBittorrent host based on VPN mode
  # When VPN enabled: cross-seed shares gluetun's network namespace with qBittorrent,
  #                   so they communicate via localhost
  # When VPN disabled: cross-seed is on arr-network, uses container hostname
  effectiveQbtHost = if qbt.vpn.enable then "localhost" else cfg.qbittorrentHost;

  # Build Torznab URL list for config
  # Always use the reverse proxy URL for Prowlarr since it's accessible from
  # both VPN and non-VPN network configurations
  torznabUrlList = lib.concatMapStringsSep ",\n    " (
    id:
    ''"https://prowlarr.gyarmathy.co/${toString id}/api?apikey=${
      config.sops.placeholder."media-stack/prowlarr/api"
    }"''
  ) cfg.torznabIndexerIds;

  # The complete config.js content as a Nix string
  # Using sops.placeholder for secret interpolation
  configContent = ''
    // Cross-seed v6 configuration
    // Generated by NixOS - manual edits will be overwritten on rebuild
    // Documentation: https://www.cross-seed.org/docs/basics/options

    "use strict";

    module.exports = {
      // ========================================================================
      // TORZNAB INDEXERS (Private Trackers Only)
      // ========================================================================
      torznab: [
        ${torznabUrlList}
      ],

      // ========================================================================
      // TORRENT CLIENT CONNECTION
      // ========================================================================
      // Host is ${effectiveQbtHost} because:
      // ${if qbt.vpn.enable then "VPN mode: cross-seed shares gluetun's network namespace with qBittorrent" else "Direct mode: cross-seed uses arr-network container hostname"}
      torrentClients: [
        "qbittorrent:http://${config.sops.placeholder."media-stack/qbittorrent/username"}:${
          config.sops.placeholder."media-stack/qbittorrent/password"
        }@${effectiveQbtHost}:8080",
      ],

      // Use torrents from client for matching (recommended)
      useClientTorrents: true,

      // ========================================================================
      // LINKING CONFIGURATION
      // Hardlinks allow seeding without duplicating data
      // ========================================================================
      linkDirs: ["${cfg.linkDir}"],
      linkType: "${cfg.linkType}",
      linkCategory: "${cfg.linkCategory}",
      flatLinking: ${boolToJs cfg.flatLinking},

      // ========================================================================
      // DATA DIRECTORIES
      // For data-based matching (finds matches in your media library)
      // ========================================================================
      dataDirs: [
        "/data/tv",
        "/data/movies",
      ],

      // ========================================================================
      // MATCHING SETTINGS
      // ========================================================================
      matchMode: "${cfg.matchMode}",
      fuzzySizeThreshold: 0.02,
      includeSingleEpisodes: ${boolToJs cfg.includeSingleEpisodes},
      seasonFromEpisodes: ${nullableToJs cfg.seasonFromEpisodes},
      includeNonVideos: ${boolToJs cfg.includeNonVideos},

      // ========================================================================
      // SEARCH SCHEDULING
      // ========================================================================
      searchCadence: "${cfg.searchCadence}",
      rssCadence: "${cfg.rssCadence}",
      excludeOlder: "${cfg.excludeOlder}",
      excludeRecentSearch: "${cfg.excludeRecentSearch}",
      delay: ${toString cfg.delay},

      // ========================================================================
      // INJECTION SETTINGS
      // ========================================================================
      action: "inject",
      skipRecheck: ${boolToJs cfg.skipRecheck},
      autoResumeMaxDownload: ${toString cfg.autoResumeMaxDownload},
      duplicateCategories: false,

      // ========================================================================
      // API CONFIGURATION
      // ========================================================================
      host: "0.0.0.0",
      port: ${toString cfg.port},

      // ========================================================================
      // OUTPUT DIRECTORIES
      // ========================================================================
      outputDir: null,
      torrentDir: null,
      maxDataDepth: ${toString cfg.maxDataDepth},
      snatchTimeout: "${cfg.snatchTimeout}",
    };
  '';
in
{
  options.cg.service.cross-seed = {
    enable = lib.mkEnableOption "cross-seed for private tracker ratio building";

    port = lib.mkOption {
      type = lib.types.port;
      default = 2468;
      description = "Port for cross-seed API";
    };

    torznabIndexerIds = lib.mkOption {
      type = lib.types.listOf lib.types.int;
      default = [ ];
      example = [
        1
        3
        5
      ];
      description = ''
        List of Prowlarr indexer IDs for your PRIVATE trackers.

        To find indexer IDs:
        1. Go to Prowlarr -> Indexers
        2. Click on an indexer
        3. The ID is in the URL: /indexers/{ID}

        Only add PRIVATE trackers - public trackers provide little ratio benefit.
      '';
    };

    qbittorrentHost = lib.mkOption {
      type = lib.types.str;
      default = "qbittorrent";
      description = ''
        Hostname for qBittorrent connection when VPN is DISABLED.
        When VPN is enabled, this is automatically set to "localhost" since
        cross-seed shares the gluetun network namespace with qBittorrent.
      '';
    };

    # Linking options
    linkDir = lib.mkOption {
      type = lib.types.str;
      default = "/data/downloads/cross-seed";
      description = "Directory for cross-seed hardlinks (must be on same volume as downloads)";
    };

    linkType = lib.mkOption {
      type = lib.types.enum [
        "hardlink"
        "symlink"
        "reflink"
      ];
      default = "hardlink";
      description = "Type of links to create";
    };

    linkCategory = lib.mkOption {
      type = lib.types.str;
      default = "cross-seed";
      description = "qBittorrent category for cross-seeded torrents";
    };

    flatLinking = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Use flat linking (v5 style) instead of tracker subdirectories";
    };

    # Matching options
    matchMode = lib.mkOption {
      type = lib.types.enum [
        "safe"
        "flexible"
        "partial"
      ];
      default = "flexible";
      description = ''
        Matching strictness:
        - safe: Exact matching only
        - flexible: Allows renamed files (recommended for media libraries)
        - partial: Most permissive, finds all possible matches
      '';
    };

    includeSingleEpisodes = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Include single episodes in searches";
    };

    seasonFromEpisodes = lib.mkOption {
      type = lib.types.nullOr lib.types.float;
      default = 1.0;
      description = "Match season packs when you have this ratio of episodes (null to disable)";
    };

    includeNonVideos = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Include non-video torrents in searches";
    };

    skipRecheck = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Skip rechecking torrents after injection";
    };

    # Scheduling options
    searchCadence = lib.mkOption {
      type = lib.types.str;
      default = "1 day";
      description = "How often to run bulk searches";
    };

    rssCadence = lib.mkOption {
      type = lib.types.str;
      default = "30 minutes";
      description = "How often to check RSS feeds";
    };

    excludeOlder = lib.mkOption {
      type = lib.types.str;
      default = "2 weeks";
      description = "Exclude torrents first seen more than this long ago";
    };

    excludeRecentSearch = lib.mkOption {
      type = lib.types.str;
      default = "3 days";
      description = "Exclude torrents searched more recently than this";
    };

    delay = lib.mkOption {
      type = lib.types.int;
      default = 30;
      description = "Seconds to pause between searches";
    };

    autoResumeMaxDownload = lib.mkOption {
      type = lib.types.int;
      default = 52428800; # 50MB
      description = "Auto-resume torrents smaller than this (bytes) after recheck";
    };

    maxDataDepth = lib.mkOption {
      type = lib.types.int;
      default = 4;
      description = "Maximum depth to search in dataDirs";
    };

    snatchTimeout = lib.mkOption {
      type = lib.types.str;
      default = "30 seconds";
      description = "Timeout for snatching torrent files";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = stack.enable;
        message = "cross-seed requires media-stack to be enabled";
      }
      {
        assertion = qbt.enable;
        message = "cross-seed requires qbittorrent to be enabled";
      }
      {
        assertion = cfg.torznabIndexerIds != [ ];
        message = ''
          cross-seed requires at least one Torznab indexer ID.
          Set cg.service.cross-seed.torznabIndexerIds to your private tracker IDs.
        '';
      }
      {
        assertion =
          cfg.seasonFromEpisodes == null || cfg.seasonFromEpisodes >= 1.0 || cfg.matchMode == "partial";
        message = "seasonFromEpisodes below 1.0 requires matchMode = 'partial'";
      }
    ];

    # Sops secrets
    sops.secrets = {
      "media-stack/prowlarr/api" = { };
      "media-stack/qbittorrent/username" = { };
      "media-stack/qbittorrent/password" = { };
    };

    # Sops template generates config.js with secrets interpolated
    sops.templates."cross-seed-config.js" = {
      content = configContent;
      owner = stack.user;
      group = stack.group;
      mode = "0640";
    };

    # Create directories
    systemd.tmpfiles.rules = [
      "d ${stack.configPath}/cross-seed 0775 ${stack.user} ${stack.group} -"
      "d ${stack.configPath}/cross-seed/output 0775 ${stack.user} ${stack.group} -"
      "d ${stack.dataPath}/downloads/cross-seed 2775 ${stack.user} ${stack.group} -"
    ];

    # Container definition
    virtualisation.oci-containers.containers.cross-seed = {
      image = "ghcr.io/cross-seed/cross-seed:6";
      user = "${toString config.users.users.${stack.user}.uid}:${
        toString config.users.groups.${stack.group}.gid
      }";
      volumes = [
        "${stack.configPath}/cross-seed:/config"
        # Mount the sops-generated config.js into the container
        "${config.sops.templates."cross-seed-config.js".path}:/config/config.js:ro"
        # Full data directory for hardlink support
        "${stack.dataPath}:/data"
      ];
      environment = {
        TZ = config.time.timeZone;
      };
      cmd = [ "daemon" ];
      dependsOn = lib.optionals qbt.vpn.enable [ "gluetun" ];
      extraOptions = [
        "--pull=newer"
      ]
      ++ (
        if qbt.vpn.enable then
          [
            "--network=container:gluetun"
          ]
        else
          [
            "--network=arr-network"
          ]
      );
    };

    # Service dependencies
    systemd.services.podman-cross-seed = {
      after = [
        "podman-network-arr.service"
      ]
      ++ lib.optionals qbt.vpn.enable [ "podman-gluetun.service" ];
      requires = [ "podman-network-arr.service" ];
    };

    # Firewall (only if not behind VPN)
    networking.firewall.allowedTCPPorts = lib.mkIf (!qbt.vpn.enable) [ cfg.port ];
  };
}
