# Unpackerr - Extracts archived releases for Sonarr/Radarr
#
# Runs as a native systemd service using the nixpkgs unpackerr package.
# The Go binary includes pure-Go RAR, 7z, zip extraction — no external
# unrar/7z binaries needed.
#
# NOTE:
# When running on homelab02 (NAS), unpackerr talks to Sonarr/Radarr
# on homelab01 via their FQDNs. When running on homelab01, it could
# use localhost.
#
# SOPS SECRETS REQUIRED:
# - media-stack/sonarr/api
# - media-stack/radarr/api
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.cg.service.unpackerr;
  stack = config.cg.service.media-stack;

  sonarrUrl = "https://sonarr.${config.cg.fleet.domain}";
  radarrUrl = "https://radarr.${config.cg.fleet.domain}";

  # Generate the TOML config file
  configFile = pkgs.writeText "unpackerr.conf" ''
    ## Unpackerr configuration - generated by NixOS

    debug = false
    quiet = false
    activity = false
    log_queues = "1m"

    # Log to the systemd journal (stdout) — no separate file needed
    log_file = ""

    interval = "2m"
    start_delay = "1m"
    retry_delay = "5m"
    max_retries = 3
    parallel = 1
    file_mode = "0644"
    dir_mode = "0755"

    [[sonarr]]
      url = "${sonarrUrl}"
      api_key = "filepath:/run/secrets/media-stack/sonarr/api"
      paths = ["${stack.dataPath}/downloads/complete"]
      protocols = "torrent,TorrentDownloadProtocol"
      timeout = "10s"
      delete_delay = "5m"
      delete_orig = false

    [[radarr]]
      url = "${radarrUrl}"
      api_key = "filepath:/run/secrets/media-stack/radarr/api"
      paths = ["${stack.dataPath}/downloads/complete"]
      protocols = "torrent,TorrentDownloadProtocol"
      timeout = "10s"
      delete_delay = "5m"
      delete_orig = false

    ## Watch folder — catches archives not tracked by Starr apps
    [[folder]]
      path = "${stack.dataPath}/downloads/complete"
      move_back = true
      delete_files = false
      delete_original = false
      disable_log = false

    [folders]
      interval = "1m"
  '';
in
{
  # Reads config.cg.fleet, so it declares it - see modules/nixos/fleet.nix.
  imports = [ ../../nixos/fleet.nix ];

  options.cg.service.unpackerr = {
    enable = lib.mkEnableOption "Archived release unpacker";
  };

  config = lib.mkIf cfg.enable {
    # Require media-stack infrastructure
    assertions = [
      {
        assertion = stack.enable;
        message = "unpackerr requires media-stack to be enabled (cg.service.media-stack.enable = true)";
      }
    ];

    # Sops secrets for API keys
    sops.secrets = {
      "media-stack/sonarr/api" = {
        owner = stack.user;
        group = stack.group;
        mode = "0400";
      };
      "media-stack/radarr/api" = {
        owner = stack.user;
        group = stack.group;
        mode = "0400";
      };
    };

    # Create config directory
    systemd.tmpfiles.rules = [
      "d ${stack.configPath}/unpackerr 0775 ${stack.user} ${stack.group} -"
    ];

    # Systemd service
    systemd.services.unpackerr = {
      description = "Unpackerr - Archive Extractor for Starr Apps";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${pkgs.unpackerr}/bin/unpackerr -c ${configFile}";
        Restart = "on-failure";
        RestartSec = "10s";

        # Run as the media stack user for correct file permissions
        User = stack.user;
        Group = stack.group;

        # Hardening
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;

        # Allow read/write to media paths and config
        ReadWritePaths = [
          stack.dataPath
          "${stack.configPath}/unpackerr"
        ];

        # Allow read access to secrets
        ReadOnlyPaths = [
          "/run/secrets"
        ];
      };
    };
  };
}
