# SOPS configuration
# Add your age public keys here

keys:
  - &users:
    - &coryg age1g02vwy6867g9v4w58d4v52h3q37slhd0gjyygh9eramdfshw0ats0wkc5x
  - &hosts:
    - &xps15 age1aqvdthnw8k7wn3z90qf8f8d3fupchhf55ecdafn5yr4axad75f3qvst4dg

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
        - *coryg
        - *xps15
  
  - path_regex: hosts/.*/secrets\.yaml$
    key_groups:
      - age:
        - *coryg
